server:
  port: 8080

spring:
  profiles:
    active: @profileActive@
  application:
    name: cnaworld-base
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:log4j2/log4j2-spring.xml

mybatis-plus:
  global-config:
   db-config:
      logic-delete-field: deletedBD # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      #对应数据库 0 未删除 1 已删除
      logic-not-delete-value: 0  # 逻辑未删除值(对应数据库 ： 0)
      logic-delete-value: 1  # 逻辑已删除值(对应数据库 ： 1)
  mapper-locations: classpath*:cn/cnaworld/base/infrastructure/repository/*/orm/mapper/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.cnaworld.base.infrastructure.repository.*.orm.*.po,cn.cnaworld.base.domain.*.model
  configuration:
   call-setters-on-nulls: true #查询语句中某些字段值为null时依旧返回


cnaworld:
  repository-lazy:
    enable: true
    agg-package: "cn/cnaworld/base/domain/*/model/*"
  mybatis-plus:
    auto-field-encrypt: true #使用对象进行CRUD时，若字段上存在@CnaFieldEncrypt注解则会自动加密解密
    auto-insert-fill: true #数据初始化时默认填充，insert时，自动获取fill-strategy-field 中的属性进行填充。
    function-extension: true #扩展逻辑删除相关方法，提供逻辑恢复和直接删除扩展方法。默认true开启。
    snow-flake: true #提供16位雪花ID实现。默认true开启。
    optimistic-locker: true #提供乐观锁实现 OptimisticLockerInnerInterceptor。默认true开启。
    fill-strategy-field: #数据初始化时默认填充属性集合
      - field-name: "createTimeDb" #需填充的entity字段名称，需要注解 @TableField(value = "create_time_db",fill = FieldFill.INSERT) 中开启fill = FieldFill.INSERT
        field-class: java.time.LocalDateTime #默认填充字段类型，Date 、Timestamp 、 LocalDateTime 默认取当前时间，Long 、Integer 默认取0。
      - field-name: "updateTimeDb"
        field-class: java.time.LocalDateTime #填充值处理器，实现FieldProcessor的getFieldValue方法，返回值作为属性填充值。
      - field-name: "deletedDb"
        field-value: false #填充值
    field-encrypt: #使用对象进行CRUD时，若字段上存在@CnaFieldEncrypt注解则会自动加密解密
      keys: Ssadasa123dsfsda21sdasd #加密密钥

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    # 原生页面路径
    path: /swagger-ui.html
    # 接口组排序规则
    tags-sorter: alpha
    # 接口排序规则
    operations-sorter: alpha
  api-docs:
    # 配置文件路径
    path: /v3/api-docs
  # 分组扫描配置
  group-configs:
    # 分组名称
    - group: 'cnaworld'
      #扫描规则
      paths-to-match: '/**'
      #扫描包
      packages-to-scan: cn.cnaworld.base
# knife4j的增强配置，不需要增强可以不配
knife4j:
  #开启增强
  enable: true
  setting:
    #中文模式
    language: zh_cn
    #是否开启自定义Footer
    enable-footer-custom: true
    #自定义Footer内容
    footer-custom-content: cnaworld
    #是否开启动态参数调试功能
    enable-dynamic-parameter: true
    #是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
    enable-version: true